---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 9.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: emqx
      namespace: home
  values:
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.26.0
    env:
      TZ: '${TIMEZONE}'
      ZIGBEE2MQTT_DATA: /data
    ingress:
      main:
        enabled: true
        ingressClassName: 'nginx'
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt-production'
        hosts:
          - host: 'zigbee2mqtt.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - 'zigbee2mqtt.${SECRET_DOMAIN}'
            secretName: 'zigbee2mqtt-tls'

    persistence:
      config:
        enabled: true
        existingClaim: zigbee2mqtt-config-v1
        mountPath: '/data'
    config:
      homeassistant: true
      device_options:
        retain: true
      permit_join: false
      mqtt:
        base_topic: zigbee2mqtt
        server: 'tcp://192.168.0.242:1883'
        user: '${SECRET_MQTT_USERNAME}'
        password: '${SECRET_MQTT_PASSWORD}'
      serial:
        port: '/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0a7307af5593eb11baf21b4f3d98b6d1-if00-port0'
      advanced:
        log_output:
          - console
        network_key:
          - 204
          - 61
          - 75
          - 23
          - 44
          - 230
          - 24
          - 203
          - 53
          - 5
          - 248
          - 32
          - 50
          - 84
          - 44
          - 159
      frontend:
        port: 8080
