---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app zigbee2mqtt
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: node-feature-discovery
      namespace: kube-system
    - name: emqx
      namespace: home
  values:
    fullnameOverride: *app
    image:
      repository: koenkk/zigbee2mqtt
      tag: 1.28.4
    env:
      TZ: "${TIMEZONE}"
      ZIGBEE2MQTT_DATA: /data
    service:
      main:
        ports:
          http:
            port: 8080
          metrics:
            enabled: true
            port: 80
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt-production'
          hajimari.io/enable: "true"
          hajimari.io/icon: zigbee
          hajimari.io/appName: Zigbee2MQTT
        hosts:
          - host: &host "zigbee2mqtt.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    securityContext:
      privileged: true
    persistence:
      config:
        enabled: true
        existingClaim: zigbee2mqtt-config-v1
        mountPath: "/data"
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/ttyUSB0
        hostPathType: CharDevice
    # nodeSelector:
    #   feature.node.kubernetes.io/custom-zigbee: "true"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 700Mi
