---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 9.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: mosquitto
      namespace: home
  values:
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.25.1
    env:
      TZ: America/New_York
      ZIGBEE2MQTT_DATA: /data
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        hosts:
          - host: "zigbee2mqtt.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "zigbee2mqtt.${SECRET_DOMAIN}"
            secretName: zigbee2mqtt-tls
    persistence:
      config:
        enabled: true
        existingClaim: zigbee2mqtt-config-v1
        mountPath: "/data"
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/ttyUSB0
        hostPathType: CharDevice
    # These config values are not what is my current state of zigbee2mqtt
    # It's merely a guide for the initial start up on a fresh install
    # Everything after the first start is managed in the UI
    config:
      homeassistant: true
      device_options:
        retain: true
      permit_join: false
      mqtt:
        base_topic: zigbee2mqtt
        server: "tcp://192.168.0.242:1883"
        user: "${SECRET_MQTT_USERNAME}"
        password: "${SECRET_MQTT_PASSWORD}"
      serial:
        port: /dev/ttyUSB0
      advanced:
        log_output:
          - console
        network_key: GENERATE
        pan_id: GENERATE
      frontend:
        port: 8080
