---
# Samsung 990 PRO 1TB (eui.0025384261a12052) is used as a raw block device by Rook-Ceph
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-hostpath
provisioning:
  diskSelector:
    match: system_disk
  minSize: 10GiB
  maxSize: 100GiB
