---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
labels:
  - pairs:
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/instance: home-assistant
