---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-config-v1
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
