kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mosquitto
    namespace: home
stringData:
    mqtt.conf: ENC[AES256_GCM,data:2agWy81hl8ZEaCZXMBVXOsGZ4MbZZxw7OonhdkqwbGDZqMLHrbhckjsjT5t73LQFy0Vx75vZSPYKEfB2QwOLcZS3G/Gl4AYi/8602DA2D5qprdGo7aora2ebU4i6kEw=,iv:t7yfUaWokAtJYgDLHGDw2qYJw29ZjUVDtXyDa2vrLW0=,tag:sbhsMFTDY2CDNRHDhIVniA==,type:str]
    mosquitto_pwd: ENC[AES256_GCM,data:AiIKn3OGi0UyGPdXhJmZi3wtre/qw11lB9G76IC+dr2frfxlQl4RMPq3odvrAJQVVu2oTjMrxdct6ivr9fgKq96/E/ecNszw/xah+tpDN475z56Ymj25r735nR/kutVXAyDE0OWNcu+jWlX8BHq0XvbXK20=,iv:ZUHYQNGtllNQbqk9dJZWkJ2TPE4MLFkgkTVPPKK1xNY=,tag:8X3WDjmDuW4bobMKiyMMvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNnRGRm5pd2xIVU1UZlNH
            Q0V4bVZEcWRGdFcrb28reFh6N1BYMzJheXpvCjY2RzF4RHNDMThLc3huNkFOVEZ6
            Vy81RmdXT2RxOEpiREoxNXZGczJMUHMKLS0tIE5jb2RaTGNJczY5Q3ZMR2Y4eG5R
            N2svWUEyQ2w3T1R2L2h3c3ViQXNnNUUKfApZNnZfkXQdsjlgaXoySx00rUDhdejz
            5DfvWK7ri7B/gPmJFtDPsikQ920WmcRJZm+wO5e/qYd9CarsHomv6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-23T23:37:35Z"
    mac: ENC[AES256_GCM,data:m3+9zXntIUkMR3rM+RTGn48GCs0m5k5sEERuxZL2NJZUA97LyBsic2SDmE72NTb0iy+tOY6h4V859RUjphV7M4p6cTStS56dRhW+1G0OSX+wKLAF+H8r2mqIm9u7/KXlbYYCbrqbnZdXxqzoeM6ImVlgXRAyvCNI2a1ikrpeyP8=,iv:eHAOyCPfLUU0nNPBrZh2lWniUXuP363nJ42SlFGKRd0=,tag:Mc0NAEA/Q/AYWydt/mft7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
