kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mosquitto
    namespace: home
stringData:
    mqtt.conf: ENC[AES256_GCM,data:lg6pePGkPbCLyDQmJMOgFOZXEXMLTvTWREg5+Kuix4QuWNiwsD4bgmgU54rkAIqNvEeojzWHpBEZIzLFE2VqaBTNS/a2MEpQHAgUU++qDR3KMxcS95lL97bpSyga1Yg=,iv:jIY71+zT7CjZxh2IYTIGBjk9zFFvPW5tYmkUNYaH8Q8=,tag:eZc7fxqusQSnkz87d/BtPA==,type:str]
    mosquitto_pwd: ENC[AES256_GCM,data:s/VTKU6xkOVe469xBrF4l1zTMfCr19BjbTKbDWgX17xwbX8+VFpcHjGcwmb0k69/1LAn9O/dWn+BNZHB3yEzh7Vv8UZLTVSKvdD1GePqDr5M1ynrbD03GBBaARUJRMx/xIJxp4kvaD3R0Ff6lE5vzpA/rUA=,iv:ud0RRgf75BpuRzFuFhaiLebODZulq7jjOYztvSR/4O8=,tag:nMa+tamBGgnRHyvQdgR0bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNnRGRm5pd2xIVU1UZlNH
            Q0V4bVZEcWRGdFcrb28reFh6N1BYMzJheXpvCjY2RzF4RHNDMThLc3huNkFOVEZ6
            Vy81RmdXT2RxOEpiREoxNXZGczJMUHMKLS0tIE5jb2RaTGNJczY5Q3ZMR2Y4eG5R
            N2svWUEyQ2w3T1R2L2h3c3ViQXNnNUUKfApZNnZfkXQdsjlgaXoySx00rUDhdejz
            5DfvWK7ri7B/gPmJFtDPsikQ920WmcRJZm+wO5e/qYd9CarsHomv6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-14T21:29:11Z"
    mac: ENC[AES256_GCM,data:PGHNQNx6UP4W+5NGNhfgZCNcDJaD0WelGNqWD7B+/qLzhQfYMHpd+vdnl7qbqou4E2KLIqH7WuU8I0ka4tG8MsLLUvyHg6+GwQc4q0337Nv5zSjYWL6HQuY6HJXgv+ZmAifky5zRw8VJ4viB7Jq2sok/IRpajeLyZrbkCO+XrHk=,iv:fqxljcvWy3kCULBvaAv1xyWR8dsCoiALaBMPMlk9icc=,tag:Fdlvap7lhDld8JteLJiNIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
