kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mosquitto
    namespace: home
stringData:
    mqtt.conf: ENC[AES256_GCM,data:JQBxq/vZT9+gpLBwKuKs7HAMNUUA1vsb0G2e6uNt9nbmqH2nqfFZkmAynoI7MDBJF9FmhnefBGL6mdZhveHehJCF2lNamlZw32JsxWHIEnbvMY7cf9PpZbm4DF43J3QpL7D7Bp6ga4zcNoYapJ4KAqt+P1xfJFWMD++o456SusJCoNLyqyDiLSNQKQ==,iv:VKrBYhg5VJjMvIs7GMp9SHDfyRcIlA5Ui8lAnRr+Ino=,tag:5Z6+HRN52BGFZz6ZMm6jVg==,type:str]
    mosquitto_pwd: ENC[AES256_GCM,data:Cwb6mzUyouzKLKYAUl8fB8UEdnrLi47KgTuZ24NNRlI3Q9NTyD7ZfbCEpjpQgwSvPlgHMznIGVqkmxdS3LUOp63p8vpvGhpfA1HDdGK/thHywC9rPkP4oMU8IU6us4lpNbEF9Y39CFRyb48iQPI9td+GYrpL,iv:ob9qqvGBRL8WRUbovEmGxi9JRT/3tyQiE0ihTEo4DOc=,tag:1mAhD11T6SK9xlq3n8DY/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNnRGRm5pd2xIVU1UZlNH
            Q0V4bVZEcWRGdFcrb28reFh6N1BYMzJheXpvCjY2RzF4RHNDMThLc3huNkFOVEZ6
            Vy81RmdXT2RxOEpiREoxNXZGczJMUHMKLS0tIE5jb2RaTGNJczY5Q3ZMR2Y4eG5R
            N2svWUEyQ2w3T1R2L2h3c3ViQXNnNUUKfApZNnZfkXQdsjlgaXoySx00rUDhdejz
            5DfvWK7ri7B/gPmJFtDPsikQ920WmcRJZm+wO5e/qYd9CarsHomv6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-12T03:19:11Z"
    mac: ENC[AES256_GCM,data:LIdDni1N2cdImC0eQ9PrQM4L9tivcItARXOQy+bTbGi6YnGLzbgMY8OzgLOEO8NTcrdLODAzsv8IamP2D0E0YsfNX39TGl2Pi/BfV/NFvs9L9gVbRQAkz6qCAxzgScCjTX6Nyh9UOLTlESknA9AzZleAhhWZh6kndXHv59LQF3Q=,iv:5XoGrF7QUHU7pIT9EVg+qEz2wXPPii1m7EPa+kzi2SQ=,tag:AuvWljLmE2EJtThfvOMq9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
