kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mosquitto
    namespace: home
stringData:
    mqtt.conf: ENC[AES256_GCM,data:lg6pePGkPbCLyDQmJMOgFOZXEXMLTvTWREg5+Kuix4QuWNiwsD4bgmgU54rkAIqNvEeojzWHpBEZIzLFE2VqaBTNS/a2MEpQHAgUU++qDR3KMxcS95lL97bpSyga1Yg=,iv:jIY71+zT7CjZxh2IYTIGBjk9zFFvPW5tYmkUNYaH8Q8=,tag:eZc7fxqusQSnkz87d/BtPA==,type:str]
    mosquitto_pwd: ENC[AES256_GCM,data:/0PJZGbAeoNEstgNjAP4EpT1nKAQv0sXI26BCa59dUmo0lO1DJB8S4G+2acz1es8EKUCex+jYJsAk84G4uHfeFWnxZE+ovTLzw8DbPmKEKHs49B98/Rz9ETlhsk2xjzSOLwHop3lKHIORDAr1qtLlOYHrVE=,iv:Ubanz9rXjUFw+nASTcDPzjs0qDQ3pusYa5iwrtGPI7I=,tag:G8KIDfglAnuaGQE9rFY0Bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNnRGRm5pd2xIVU1UZlNH
            Q0V4bVZEcWRGdFcrb28reFh6N1BYMzJheXpvCjY2RzF4RHNDMThLc3huNkFOVEZ6
            Vy81RmdXT2RxOEpiREoxNXZGczJMUHMKLS0tIE5jb2RaTGNJczY5Q3ZMR2Y4eG5R
            N2svWUEyQ2w3T1R2L2h3c3ViQXNnNUUKfApZNnZfkXQdsjlgaXoySx00rUDhdejz
            5DfvWK7ri7B/gPmJFtDPsikQ920WmcRJZm+wO5e/qYd9CarsHomv6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-25T02:04:25Z"
    mac: ENC[AES256_GCM,data:fFimh0TOEs6P3NgHCJE6G51DLwMuNVvwmTue0eUdaB2VsSXzUhw0pm2zIZW/Bs8w4gVrtU19in0Ob4ClbiodhCeW6gtsB+D8C75PbSZ8Hc+lUxHs3z0zapFuuXFQh0IwC+ysEAaAn4Dps/oKxgn8NAdOj/POL2QEA+YPUuC9o5U=,iv:SkzLOyld+SdRIFeNmkLNn0K1yciDvwpCoPNytf+D07w=,tag:dv5CjrpOQzg/q3rmDM//JQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
