---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: emqx
      namespace: home
  values:
    image:
      repository: ghcr.io/homeassistant/home-assistant
      tag: 2022.9.6
    env:
      TZ: "${TIMEZONE}"
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        type: LoadBalancer
        externalIPs: ["${SVC_HOME_ASSISTANT_ADDR}"]
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "home-assistant"
          hajimari.io/appName: Hass
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "hass-tls"
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/k8s-at-home/code-server
          tag: v4.6.0
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            hajimari.io/enable: "true"
            hajimari.io/icon: microsoft-visual-studio-code
            hajimari.io/appName: Hass Config
          hosts:
            - host: &host "hass-config.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *host
        volumeMounts:
          - name: config
            mountPath: /config
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 4000Mi
