# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant
    namespace: home
stringData:
    HASS_LATITUDE: ENC[AES256_GCM,data:GdRyLBYj/qTn,iv:QkJDG9gzxNccFuBoFlmdkEgRAHLb6fsRguADs8izdE8=,tag:rhZr0KIwCoUSDoAhsvRFLQ==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:RJFyinDLTVZvHw==,iv:bga6e7+3+hJ4BQcWEMMM3OKDBSH9POptpRT7CujFGEY=,tag:zrW7tTgfz/3SMO/MsKyJCg==,type:str]
    HASS_PIRATE_WEATHER_API_KEY: ENC[AES256_GCM,data:KPGRR5LY+Y3wG/tbZ1OXoS8pGHn1JzW8jkdVrrLaF8KwARFQgJ4YWg==,iv:GtONFnaWi1aMFTbnS+qFKAh6+jeTNgW872KqpZKtEVs=,tag:X2b0xbOPHHbUgNcMuWm6XA==,type:str]
    HASS_CLOUD_EMAIL: ENC[AES256_GCM,data:PCzjr6J3LaLuMvuJXF48QdV2eg==,iv:FdWvheSc7GTDvglHwOsyFgbJQvU8b/80Fl1RZF9DP1g=,tag:iYgbdKgmjlaEu866vHE67w==,type:str]
    HASS_CLOUD_PASSWORD: ENC[AES256_GCM,data:rzINq41fOf4=,iv:LpB0WLdOiCZieKVRMNn2T20Uu/7fXJwsMS8PZL+6iJs=,tag:DfvrZCAQ5/7Ri8GX1vCigA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZTRsNU5jd3dEY3BzZ3ZE
            aEQ1aVJqS2ZMNUw5K3BMZTlHc0psMDNoeEJjCm8wMElPQ0dXcUpGTXZDWDNQOXJn
            YWQzQ2dtQnl6MXF4bS9xNUwwRHFKYWsKLS0tIFNBOHZrRWpXM1ROYmZ2aXhGdldN
            VTNPSW5MV0xpbmtTVGNzb0kxc25xNHcK/gCTMxZBaEGERoq7Xc8upsf7OYe/MFk0
            TYU38MinytF8dKP+G2yqL/caBcTGXv4ynWLxuua/afvBhLMnyuXHLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-22T00:59:29Z"
    mac: ENC[AES256_GCM,data:GnR+ogj1XQ5t1Pk+xSFg8eECZ+eDMabvzWWvy9uRLb9Q5v26u2Q8gF4Hfj08AVD87xoJJjMBxcmh3X+33PK0nXHdu2jot8YgLWWVx+XK+hHOJ2ZksFHyRSkspjHBwMQIZYBzhZ36rAmaq4tuzGNRVbh3O6RQbE9Ec99fTSA5rxc=,iv:PLsg0m5J33K7vSHsBxU2athUM2MOTtZRczrE5eePz4Q=,tag:TKeavCEc+vA5ly3arc4eKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
