# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant
    namespace: home
stringData:
    HASS_LATITUDE: ENC[AES256_GCM,data:KcbkCYR99g==,iv:Iy7WfNb/aP+K0X2neB33OF1lHpvFfKqz301EZtDxcDM=,tag:NLhJWjnO5eK18g7C6/uVTA==,type:float]
    HASS_LONGITUDE: ENC[AES256_GCM,data:8YokBmLlD035,iv:pD7pqOmvbr6pcU7s0q7mXO7y/vaGA8RzAOGdhV3d4Sk=,tag:AMS66/w7qSvJ+DXK6nbpig==,type:float]
    HASS_PIRATE_WEATHER_API_KEY: ENC[AES256_GCM,data:KPGRR5LY+Y3wG/tbZ1OXoS8pGHn1JzW8jkdVrrLaF8KwARFQgJ4YWg==,iv:GtONFnaWi1aMFTbnS+qFKAh6+jeTNgW872KqpZKtEVs=,tag:X2b0xbOPHHbUgNcMuWm6XA==,type:str]
    HASS_CLOUD_EMAIL: ENC[AES256_GCM,data:PCzjr6J3LaLuMvuJXF48QdV2eg==,iv:FdWvheSc7GTDvglHwOsyFgbJQvU8b/80Fl1RZF9DP1g=,tag:iYgbdKgmjlaEu866vHE67w==,type:str]
    HASS_CLOUD_PASSWORD: ENC[AES256_GCM,data:rzINq41fOf4=,iv:LpB0WLdOiCZieKVRMNn2T20Uu/7fXJwsMS8PZL+6iJs=,tag:DfvrZCAQ5/7Ri8GX1vCigA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZTRsNU5jd3dEY3BzZ3ZE
            aEQ1aVJqS2ZMNUw5K3BMZTlHc0psMDNoeEJjCm8wMElPQ0dXcUpGTXZDWDNQOXJn
            YWQzQ2dtQnl6MXF4bS9xNUwwRHFKYWsKLS0tIFNBOHZrRWpXM1ROYmZ2aXhGdldN
            VTNPSW5MV0xpbmtTVGNzb0kxc25xNHcK/gCTMxZBaEGERoq7Xc8upsf7OYe/MFk0
            TYU38MinytF8dKP+G2yqL/caBcTGXv4ynWLxuua/afvBhLMnyuXHLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-21T02:47:54Z"
    mac: ENC[AES256_GCM,data:1fiLto7c1aT1TMyeLQzpwZgYGICVRPC4Bl+4EnpW/hoo0W04ZUZrFYpzQNLhvNH3WOU+Kxx+OGvyobgy7zkipPxb/ZN4qalad0o2VbIKga64CVF0r0kCV9ORa4WEiKlhWVsJvNABjSb6xUUrd4IY/FMIvlVnMODxv9eG0tuiyVU=,iv:EBgY44ms5iphi/KBuPmizW8N59Jw9if5wUxpyxmj9Jc=,tag:a05ivbAHJaNEb7TEpLy+0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
