---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: sonoff-zigbee-device
spec:
  rules:
    - # Sonoff Zigbee 3.0
      name: sonoff.zigbee
      labels:
        sonoff.feature.node.kubernetes.io/zigbee: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            class: { op: In, value: ["ff"] }
            vendor: { op: In, value: ["10c4"] }
            device: { op: In, value: ["ea60"] }
