apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:zjPw5tfFHDalmN7lXBp5Oy/ryoC3X8uC4OfpgQd6xFQLfYs1W1/6Tg==,iv:3ua+ITJNKEC5B3OylBoQeoF5UPUFEks1MQtmvBSVU4U=,tag:1kcjZI1jwvcdRc6gpNWVmw==,type:str]
sops:
  age:
    - recipient: age1r0cv0zhd3uup44g0jkktl7luk0gq8dkg22d9yxtpjs380rgle3tqkj0y23
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMDNrQWpmWW81RjJzYlhr
        TW85cmwwS3l6bTMyYUlMMnVsc2FDbmtsMFQwCm1rd2JpbDhvUGxlbXVRZUl6NUdY
        WkdwK0FCWXk3Zi81MTcrZ1I1RmVUMDAKLS0tIGF0MTBRUmozVEpISGlTSjZsa0pH
        bWFKWUR6b2JkMU90SFhDcE5CK2dOdm8K51z76e5cCCmCqAgSCgW89msaidHsdg4F
        FnanPPTBrww+DSlYCUbYHITa1UCWbEhzbYo1jSjfZRq2NxG5TkCknA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-15T20:12:16Z"
  mac: ENC[AES256_GCM,data:w7hoz9mwgoZ0Y0PsTRSsMJcwDiwR+UWypQWgnUK76ld93krzfJ1z1ZftbDtuwCEaii5+5pQ/r8qlzZGzqttVCkScgYs5nOQlwcnqyBvAlYf4DLG4RhrKdTQmT2gTH4306N/HJrQ1ZrDM6E5OyqPQ0Ta/BNizGwDlzI7p90mKvQ0=,iv:s3bsQ9zoEqCcarplQm+bWYe+V2Q3hETJSMI/F5Cvw+c=,tag:UNktUV0Zkmn6LUU+xjW5uw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
