---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nut-exporter
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: nut-exporter
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: nut
        property: NUT_USERNAME
    - secretKey: password
      remoteRef:
        key: nut
        property: NUT_PASSWORD
