apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:+R0+54XhW08emtXwwM8Bug==,iv:ahwONLSGOjwetWNDlAwLiZ5S02XliZ1Je6ysEqB/mDs=,tag:S7F6iPQGhyl9qy6Tqsgqcw==,type:str]
sops:
  age:
    - recipient: age1r0cv0zhd3uup44g0jkktl7luk0gq8dkg22d9yxtpjs380rgle3tqkj0y23
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYlZDMzZSUDVkVDFYckhC
        V1hHL1RTdnhHdnpyY1BlSWJ1bG1paUhlMkhNCjVkV0l4Q1hLTXFWaVZyVDJKdm81
        N1RKWCtycEpRSk9WcDFXcGRJazVQUGsKLS0tIGdKS3BnVWt2VVZRY3paVlJWb3VT
        bDE5OXFPVjdKd1V5UWxhTUpTclVCRDAK/ROUHdKQAPWv23z2VDWfMYfegYb1cBoD
        yYuiEz8UAwNuvdGZeP/xeYlAovV3jXJlMi1RyyheYkvLEU7NxrEkVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-15T20:12:15Z"
  mac: ENC[AES256_GCM,data:FMet8499obC4V89Mr1cj+VkK4xvDCw/BKCTrVs8a6g/7PafOLSTMI2WLf908IAKHqLYI1tb5Ucvqv1SRp6YBToqY+JaBwMqGInLX04r6NdFXrJHp85RATIP3NipRPoG1HpZXFeKQRn+AjfAkluT5eyAh0DCduDZ9kauzT5iDebw=,iv:qIVAqdLdSW3uunLdcV0fQ202QOZKqKg5gbo7lzr/7Sg=,tag:1nI+AgyJCJmImZkCFaQiYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
