# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:hvIQuJH7i1PS2QS1CDfu6n75fqsKZeqLsgOgCzaR7vaUIA9FfA==,iv:sBkPgcaU1EONHRCaQYvWOJMzd2A7zuHiRjF/qR7n24w=,tag:DtL8zW6wG1vu+dPQkoxong==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwclZmakNpc0JBcm9udU5k
            cW4zTm9NRG5BaUZHNjFMQm5tQ2tHU0lTelhNCnZRWTZuUlR1MzFsZ0ZNTEVSL0Fx
            WDNZUUhVbGVCbUg2eVdVdEFnNlpySlkKLS0tIERjenQyV3owMWYxTU9IVUxDZEFa
            WkRjcnJLQ1pSTExUWTZJcEtWbWF2TVUK+zrFPKPdvDOPBvrwv+wE6hWgnSM6nLd1
            DkNWgfWoCmel6cZ8GeQ27WQ0Z2R5ID0eKWPyC8yfOnbjYt7a8iPKqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T01:02:58Z"
    mac: ENC[AES256_GCM,data:3Md5ENQ3/BmPtgrWiw7VM7smFIvxXmhLNMgjFDEeWCx6ruPNb/CYFqXEnmQsUHz+fs4c+TCLk3j2VM1vCltB7xJEzJyK0OEwArlKc7Ig0M/xz/KYQmCLQIlVrGGmOLHEv2ZYKnxanYCoIeFB5x2K34R0rA3GuW+j99ktSYbao2I=,iv:O3Q/yRdS7H8TKC/0MmkDUkLHYjSXEJVyloX9DSDaJHA=,tag:OWslI55X0xTtEbmyx/4X4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
