---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dispatcharr-vpn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dispatcharr-vpn-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        WIREGUARD_PRIVATE_KEY: "{{ .PRIVATE_KEY }}"
        WIREGUARD_ADDRESSES: "{{ .ADDRESSES }}"
        WIREGUARD_PRESHARED_KEY: "{{ .PRESHARED_KEY }}"
  dataFrom:
    - extract:
        key: airvpn-wireguard
