apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:qFKs+nwec//GyVg5/k21e/2LE96NIVRo9s2GqUziLnA=,iv:xiTeVNVFbH1TFcyhzng9ruZQcqWCwjuqwi+NvekS4ho=,tag:1qlKZbXQW/qm8BWI1A1ikA==,type:str]
sops:
  age:
    - recipient: age1r0cv0zhd3uup44g0jkktl7luk0gq8dkg22d9yxtpjs380rgle3tqkj0y23
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFV0hvcThRME5kREFlazlp
        UTFSaGg0WWNKVzZFSEJySmdnQWYxc2ZLV0R3CjU2Y0FZemF3bGhOTmFGdWxJTjNE
        NHFFTTVacFNJWkw5SmNPdUlteHlyYUkKLS0tIGNoSWVWYmU2Ymx6QnR0M2JSTWFU
        L2ZWZDVRNmN5N3NrejdXTGtya0lVaUUKAkcb3i4I2G3Q3TVFjmsViqZpRdCSB4Hj
        zZgNXs31XLG+X43x4fDRoam4yK1im6UXmf8h5CMCVSF1k3jG8Gmufg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-15T20:12:16Z"
  mac: ENC[AES256_GCM,data:D7Fvqr6H2uKvx7MqXnRfiJr0RcXjA808V7v3SKP3sgxWe2Jn7jwE/k3PFe9Kltd5v+OG4fXQCx6JNwXyjDcJgoBjMkdd/9WRHM09Z5pEh2lq8EZNL9NAmifQ0T4jv69KOnCb1vMQ+12286PIbi0RgWjiJvPysz3f1SZwm10EzJo=,iv:sZ0pGx8feP79Mie6zC/IwrLu677Zv9JYscRszLod6Cg=,tag:OhuRKMpD+BuqU/8DKlx5CA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
