---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/New_York
  METALLB_LB_RANGE: 192.168.0.240-192.168.0.250
  METALLB_K8S_GATEWAY_ADDR: 192.168.0.250
  METALLB_INGRESS_ADDR: 192.168.0.240
  SVC_HOME_ASSISTANT_ADDR: 192.168.0.241
