kind: Secret
ansible_user: ENC[AES256_GCM,data:ufuKQ0Tz,iv:atSAmcYmq/vsivlYUKlDb0HrHjbjlzHLdqfDU/ZZUuw=,tag:r7Pd5FmdPwZF30mmr83LBQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:BqYxjfdcXiU=,iv:ND/PdAEpX+GYtK2XSi5Pgj6gDHIITdtWC0Mxhf//sp0=,tag:ZQ+tJMJU0CkEKoH/wwSjiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbVRiWHBtcThzU2F0ZkxV
            eU1BelRDVXgyRXFhcXpOZVlhVXhMSnh0V2xFCnl5QUdscGNzSjhXbk0xRE9TakRh
            cGtCN1gzYTZiTkEvM0d4amRYcHZEVFEKLS0tIDFlT2dmSTdGMDdMM0p4RlNXaitX
            QmFMcm0xN0dXVEpjdEwvZFZQNzZ3WTQKYErkxntwt5tXohky5D7nvLzj0vGimMO8
            RV1kSYUQt8J4z4mj8V8VduDVATRaDQ6Qx+gEp/68QbwGiRQ6lJayZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-09T23:08:44Z"
    mac: ENC[AES256_GCM,data:O1nPWAYG0Q4am5i5ncGwamyDCMZ5EYDJCnRTMaTLsp7yGpVf4/acLmdlQYMP4tZm7eorSTGIMvxC8cWJeDHg9PVU7xXD7SI+FUoEVnRzss1dVEaeP/21h73D2hjU4b39F8BT6QNcvyOITjl2klbxDNCfqokjISbXyrODa1qj3U8=,iv:B1VSzvKGebCDXDtZ3hKGKuEC2/pRAD4VVvWQkvomhvE=,tag:UIIrcKM4kLxn2asaDLRw/A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
