kind: Secret
ansible_user: ENC[AES256_GCM,data:aKFNkwBZ,iv:1fvUPlXxmHBsN71CqqVybztH6pLWUuQWy5dfbLCUMuI=,tag:0hbw4IAjqcuQlEj+5oz5+Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:7ma/UF+XXu0=,iv:eVgDk0ooY8c+/K6PZRODJUdFmQGseMEiL+iJwSbwo30=,tag:UsXGu7s8AMrN5Vd0SBD01Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Ym9LaHBmVHM4cDFWQ3NB
            QkhIdVV0Q2NXa2h1Z2hqYm4zUG1ESWUzd2g0CjRpQW5pUy9PWnh0Q2hYRHY3YU5O
            bHB0UXR5bnFlVUd1L010YnhsQ1BheVkKLS0tIDMvNmVwMVJYc3NHWDRZQ3Y4K2F4
            Tzd2ckZwV2p3cTNENlA1QVJNS0hhVlkKoJNXHxfQGAJ80egGGQXnv2JuNdOYgHND
            iMwZNH58SxufZ50NJGsgK4CI0jk4o/SoCRnpphTPr8Jx5n3LKrmCBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T01:02:58Z"
    mac: ENC[AES256_GCM,data:rx+jWgbsyBrMN1GXf/O+WJ60bLnivQY0L9Dh8hxJVMbs2yZ/tqnAMDAwnqJZS54nWyZLm9j4XlWPq3o8gESAWwFhJmfzPA+2kEhn7SJizpN19upENXnU+un0GZWhgFzJME4seEw0snCfsxBBQLsmlQA7FY++Dc5vSx0YazNP3TE=,iv:cAGHYPSxB+a7mWZExE2El2ckaE+a/eOBMkeHw0KXdqs=,tag:IEhExBlXgx+Y5V28FFzz0A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
