kind: Secret
ansible_user: ENC[AES256_GCM,data:ZpulXCCk,iv:LGBiS+zwy+fzuiFxKk1vdcE/VBFiis7Ko0GO5Ow64XI=,tag:JKhgHSu1EthFJRy/1gkCCg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:xIckklO6SAk=,iv:+FDsHmoRGNBPG9r8hz7Wao7XpkaRPXMg8akTQI1njek=,tag:mpZtjxSCa3hR88EV+LKYMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MGx1YkRDMjJHUW8zL3Bo
            dmxTdXBBNmo0UEM1NGowWHZmQTc1TWlXVDJZCk9EVklPaUhIeHVXNjJWM1RhTUVM
            bU52MjEwTmY0elcxMGZUVXgvRFJPUEEKLS0tIEo1S3RpQm1RTUFocFpoVG1ZSHlh
            Wk94YnlPUUpHVUowdXQreTNiOU9zLzgKbOXCLoWC6kUF4Fwkv2ABTvA0oslL52at
            ee3gTXBx+BVwvaYO5f5CHGRK0XuKyGKyHlb/AjcM6qkRb9kIqJNW6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-30T01:35:45Z"
    mac: ENC[AES256_GCM,data:dl+es0RqfvyMm8XkE3PyFSnzLNJg12L2ERYGUi97FPKAnLDaaUqDIO8bFe4X/FKHMTJ4loYXxaQOSrT7eVWRKXJfKRXroK94GkoqZ5pt0k/q7vX+xyR2Ixp4EjG++/8P88GUxK/w2j4bI8DdXV/xKeoztCcEMP3YiCQy9Vwi618=,iv:YsJ1TzaiL+50QErkEMsczdQ65MBymOC1M2KNmODHh9o=,tag:/Ckv72pgqjs6hg4qw9mRrQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
