kind: Secret
ansible_user: ENC[AES256_GCM,data:Uab2H/du,iv:WjOsFhwKpLEYBl8S1TngCJrmQBgC3H1+FNcq6cUkXNE=,tag:Hy5CJwEV4GTSoA7Wr6FSWw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:P+kPCapcnVs=,iv:0kbl1pRNEvNN9btLNws3H9cEZr65KnW/yOw9Cs3EksU=,tag:Krfutnl1Al8/SZcKIaADvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNU01a3lyNzRLdTFUVWFx
            alN0ODl1ekZDOHhNTUlORWJJbDBKbXVaM2hNCjZxZmZnUXdXWTJmZU5WcllSUGUx
            STUxNDBTUXRHR2RPRjF0UDNJeEFxaFkKLS0tIHcvdThkSW93WUcwZXRMWmpLN3Fn
            eVhDMmlnY2NTc1MveUFBZ3BaNTdUTHcK8nUeiMxwx1i9/omXnWcGd8isSLmzMkDD
            a7D4AsxLcnltguuHyYH1e9t+nanYY4vyi+cvvfalO/Fdvq5Xgti5KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-09T23:08:44Z"
    mac: ENC[AES256_GCM,data:4JsRV/ERcvw0JKfED8rnDF4mObLue9rjvLhvTUx8NCPkYbwAUajD5ZTeSKBkgo4P3i0BB/mE7E9HYo/B9yreSPJFQFuU8YS5ZkqKmnTMReLV9mQBwks/uGuyRFUe5Dr3qkGsNeqsx8hTPe5eU5g0Ap0CQD1amiD4nTuQc+bqeZM=,iv:FIPT9YX5ceCkq7YslZHHMSAw/iRpYp6ST8fcut7ey3c=,tag:Skz4Vy6VApjzizwkSXy1iQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
