kind: Secret
ansible_user: ENC[AES256_GCM,data:Pp9Lzh5z,iv:BeCsgfgPHBYZl5mqtqMoQVx2DxLDFt74lYPxECbx+r4=,tag:OpxUByxg4l8ol5BDNMk/0A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:in3vIU3eJag=,iv:f4Vr2T0e/TbDzmGB56WE8DWSX5TtLNI56vLG7g4Wef0=,tag:4p6fnQGnue3sTjV6i0scXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-03T14:15:56Z"
    mac: ENC[AES256_GCM,data:hDIwq3S/OXGnFVG8RDaF90l/WFiIqGMHVCX/76lfnQur7IKrwbxEcjvTFRwsbI9SWOFs7XCqxfyqgTsHsHFPrOU0xMw8i9qY+C3WDw3JFqk8hnumHWJaVw8NXqVPdU53BCJ1naGlE7EqvJLIzttGzHujb7AuQxmSqbiMbhddueA=,iv:+ZnxPhd69W/xcQV/j9q/rLvqLZ69SB4CtkrVQqcn7DI=,tag:IJRsa9JR0jTTGURPjyTXrg==,type:str]
    pgp:
        - created_at: "2021-10-03T14:15:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/d+47VgAezOAQ//brDdhEJSA+qpGC6qAQlqp6V9bSt0R4Zqpm/GHrVTfcGs
            0xQQ6shbe5ki3xNIM94xZeaArI60sY2GvP7olMokMQhNaOW6jtYHgl190sRWZ6ve
            lw1tX1cqyZNeS+lXXq502sifpmz9/aZpDlBjLQ5e6ccGpqkdxOLa9bWKsGXRy8QW
            dftUVAl0me7RiFkoubmbB/n/uWQcdSNF06FqkQ7o1pykGucwcPmNXSXbIbIgkRyA
            8Skf84QjvW4g9dcczyuLYVQBAMsbm18Pfkl8xcj2AK3Nbh9DnNVE3DJW8wNNu3GL
            pTvxdst8QlocxrsHdFnJZmsCQHGMniLrew0ZweRUMP2kYnrHtrM+hdGCHNJuyoGt
            iaL4O5bueLKd/FX632KQZWue8cUJvT9nhDXjg6IXEpRuuxmMsKo5oHrF6s4vJGMe
            pFmKMxvzV1G8djOqXXTj96eh8Y8w1XekQ3+ci3ftr6SFFQqCR9dxYDEClMHhG2np
            zP2erKAYNybPu1lIcKinbkOVqKBPZXAb4a1L1l/oMWc02KGthdLumZL+mmQevXB3
            9Ai8oS+bFa/VZ/MthWkdBxlXPuRQMUq7r0O7B3J+CD1USYj/O7kkMsYzjQjmX+gy
            GquemL9MgQn5DN3s2HY8p46z/czIM+ycF5MWPjuTlVMHVfgCE8YYqmRA8mj0NXvS
            XAGnLDz3x3jf1IIlua0wY4UWF1ehOkL/Dnjl+m8X0mnXvLBEZDQ7FJmw665RvE9U
            YzdHXqxifEA4rQLTKsAOSqNtoa7uRNH4OWdYRGaUGUpwkFJicjXCBsdylNhO
            =u28S
            -----END PGP MESSAGE-----
          fp: 06588319109A209D639CCE51602B7725DFBDA31B
    unencrypted_regex: ^(kind)$
    version: 3.7.1
