kind: Secret
ansible_user: ENC[AES256_GCM,data:xlzCQgSW,iv:tNqC0bbAZgi7pCbRvxTs08nXaRieNXmRopFoTu2/Ihk=,tag:+BHiaCTRdE57uDRm//YHYw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:17RglS0y0WQ=,iv:Kxyvc2OVjzUrq2TjlBqSCUN72vw8ifTIAvSq3dKc+oA=,tag:i8kb5dQAXt4ATP15ppzNbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-08T16:50:44Z"
    mac: ENC[AES256_GCM,data:2RuXvYRjKIkessfPEjdlw6E/r8IbUeENcXb9DzQlmlj0hy19ua/8OoiBWiH0c/w2SclNcGB4fNlfdQEQAe9g6i7LthEGfoonJ4Ww/87NMJT2YZ0lyR0EeMOOfVbv66l4caehRUSfcfGfiyxlm/AJkMEVF9Amgo/9xXGSltUm3CI=,iv:7cBGP333JYyaux0t0i75arDi/zU2MSJtEXbY0zB1gQM=,tag:SS8Zmy3umICf52KNafyyRw==,type:str]
    pgp:
        - created_at: "2021-10-08T16:50:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/d+47VgAezOAQ//bnQ8CJPbWwO2PAHU1S69+Po0nEXgLI6qMVU8Av+GMFqK
            ofUW6ZCTPCNyQd1rLRNTN1HZiq43S73Pwb+HfiSN8fUhcXhmdTiWk56EbgpYype7
            r60ObSeNFyzZz+vkxrvZ/PrdldD4kxUQ5UfFzOQy8LSHmpWC4wpfZHdjgbzQKhcL
            OJzwhjhPr7A1ik2wbFqFsjdBKfQteXjgA3d1Ketv6HRvIKDXcibUF+ewgBvgshnQ
            52zY6u5TTQjDjO6AIWz8YNX2nS1E7PMOeh6OHNXwpbb1EOav4veS296xHQL9uipb
            lA3pUo1+yXC6pzhchIKtbbzqirmZgYlREt675pCEKHWq6TBqPLfzbQBc8OsWdUGa
            zoUkxmtVJCIgtPSP7ACe0URb7Sztix67zBjAF+Af8fRw3O91NjPm22++LlZJ2kVC
            Kdm4rnYM6Mm6YcAsFE23CEdVNpHEjEa+us5Xaeffl5idJBlntyGAiZx4lhrZaKuQ
            L0oxQrTBHnF9sAuy4Pc9Ua1RHk1Ij/+PkioaJe+K8xEJw+NM+YlxH/LvZbLkLrXr
            SebSmwih3hXSPeG0WcKW3/uC2y2MV0HCGMq5iDVXz8PcFli+vXd37oOcokO6G0UC
            WVbnWmZraGvs74/3JGJzKdavTTteAvkvTgVWGbcF0F/Waoh+R5BlsuG5VPajT9nS
            XgGZ43QaDloxfRUmG6OeHFxluTd1mPwRwRMFoyzLtywYy0cv7DEkgcMZjH3es2E6
            adiWORfMx1N3BcgEq5tywfPgj+Vtjs3zFzep3C48Ykxh9S+T7m+KvXyLtZf9ubo=
            =wyqO
            -----END PGP MESSAGE-----
          fp: 06588319109A209D639CCE51602B7725DFBDA31B
    unencrypted_regex: ^(kind)$
    version: 3.7.1
