kind: Secret
ansible_user: ENC[AES256_GCM,data:wHjCQ5ON,iv:bf4Qxy4ImkJlrJQpp2EwJB/T+N4CRo48TPw29KCrWHk=,tag:g86ux28pnMTBtU5SpRbaLw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:45gCPn9+MZg=,iv:VZOwQbQ1mVeowehy7m7c68LmbG8Yj+tNe0rBYKtAe5E=,tag:8ly02GSNi0uHN+kOmDTP0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-08T16:50:45Z"
    mac: ENC[AES256_GCM,data:51bFaXZ/EHXkvSH6QWkmQHS5fExpkbDli2rxfwTDcOJ0k8Yx/Rm3FtiDe83hSx9/dCcaumdl3xZyD0wtDv9Zu5JcRGlOH1LyXxx3ROkrPwlj5MdQm2Un0BKFRr1ztWVMrDDdznwsJKe5lqhjtSVTDJ8+RBSqhGhob0+lCft9kR8=,iv:OKADMiGobglPu9V80tD7lmG7zSVn9Y+JB1vC0LE8q5Q=,tag:RYR6jlA30bobKBPtQet/Zg==,type:str]
    pgp:
        - created_at: "2021-10-08T16:50:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/d+47VgAezOAQ//WAMWOZW2A2o+jbtFCPYRjgNA8m7/W4oa3hCOudHoU2LN
            RfBqinkhfywqihXz15xTlfhGXNSkzcv/OheGRqp0GTxBMdbdrXG0AZthe+a8EVmm
            1V/LHS8FHPFgPUMZ4+Mz8+kEX9BehaAdbrFi29TEr1ijy0Gtkdb8PBo1cLSvjwmC
            KYyFKZcuOMGvE6cX580FB3hC18V6qZfrOoZL7GUdx1j9H2CmC1JlHMmSO/6gtp7j
            q/n5uFTLXRR4ZiRxpfUJqNevA80DsH42Sbye84CYW5qtaNs0pSYfYXhFlAKQRzhZ
            DAlagB6FTpRzj7uF2qM53ngw2YLiieP3O/yWopoTQMwqHV6RkSW+aRpMjv1B/QOt
            IPKHyJHuCyxyjSH2eGWgEyNfSLbEL6yjR4mY0+6y9DabBEJBCQxGWTdkrnIa20wF
            StGd46FQs4kimkScLiB86iNHCQzRT57yZuivpMQSizvN+7PS59lBzeRTVwpKU+eb
            bgM/iXzMrEWKCxhOfAaR2Wql4VbmH0nvtKcAhnwCUcBSI+dWxOfaymqkEUAguuJb
            QvzaOdsD5H8Rs31j1gOc8bNiE1irIgruvXdNQA/bVMZlrpeUnyNf7l5S4NBTQhAv
            VHJqhbS+ccWZo9tk5xKX/b3zWnZi1PxdSVn1ZNdc1zvJ9W0CHwYUw/cWXS1FaCfS
            XAHX8uSCmj46IlbKx6p132qalC3oQxVyLI4pT4c7aoa+l/XJXbqkWZxFt1r24duz
            gCK7cgD3tgu11x/VOgdB23ifNCFbsXyvWWtSiM0wvZFYuWpoW0qiqIrmKPcT
            =bfSm
            -----END PGP MESSAGE-----
          fp: 06588319109A209D639CCE51602B7725DFBDA31B
    unencrypted_regex: ^(kind)$
    version: 3.7.1
