kind: Secret
ansible_user: ENC[AES256_GCM,data:rlLYp0Un,iv:hBEwpz6qROfe6P2WwCWn61K3uLf8q46szUEwR+urPC0=,tag:HQFGnB1YeDzSTycV3DOs4A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:CzZbg1s8r1I=,iv:r6gq70joT4HFYWIP/ThVO+5PwWdAeF535oPEp3yt4Ag=,tag:CGIp/gQs1PraWHUMCaPnyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-08T16:50:46Z"
    mac: ENC[AES256_GCM,data:5PEr7OUHrmtI97HmAZqu1NjkfP+v0mJqYjVXpKYYzik9cio5J2kZNqFVvSu1wb7TgRTy8u89GWa4mDE6KHtl6w7NobGObFZRbK6xu+qPYP43/hNo3pejkIULty+HPvQmlu/wwFfAD03o9JbStNXxZQ2QjEsr2QhF20CEKRHnuWk=,iv:JV9R0fdUq7f68jU7l19if3leRO9u/XvlebUM/ZFSzqA=,tag:Zv8SzOfpJNcv7pjdgJhFUQ==,type:str]
    pgp:
        - created_at: "2021-10-08T16:50:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/d+47VgAezOAQ/9FaEhQDZm1VZGgKCr3Bf4kL4ndk3dj37bJmEyp0fdRkAL
            XmLoo/6xmgZ9q+RBFwL3uC3XptiTWpBgUPIRht/Ppoyq3mQo53jboDUVPbWz0agu
            uTzjABsuYRYlNJUIenF0I+pc22u7534fixyDm5/TNHRxKza/xx18UEiFxNk3+btU
            KLHll7l9E4/NzYvfWlmIEjDAJzOcbn1Ms7UpiIAaxWdNMFWJRSxrYYdQ0aUapdo9
            3waooyqgLUKeREdPzcXSR4xD0H6N1psDWJagA2nrkk2WXPiTvaCs9t9KCLWeG7xN
            TFTAYXKeop/NxZlksR+bWrRwZ0XXyOowJmELKCoFq9b2GB6aM61tGQkSD4jHnsJW
            wOSuvjzHEk5e6+8wWALkrVcolt8TL9Yc8pnGI18nOlwMj8Eruiyvgy62fttda7gw
            d5n3xcNXUnwa+XzOsc+eRTMVFsq8Eoz59fth78wrNQz1qZCFlfW216n94Sgha83C
            rhFvYy4BJrI9wdTOV9BLsLAd5ga8ZTDHv2JAPrbd2MR6RGtMRuy5FkconZtzqrRq
            3c4uc063DwUi/fFnSF7WQ57Xl2XhPRGEkm48StSS6azQNxuHayxCvnDpy8jFsYtR
            6L+CV4fSJp6qyBCWZ59ljecZDJADwiC558S/KM7yBjEikQDAsiHq4N/FTeSIRgnS
            XgFUyQzjILuY2Bb6U1BBLeTvXdRREcKZ0TlI5AKscEv2NoF+rdz2aEwaMU8UNJVb
            DlOA806KwQZ/dqxkNyD9jCdGhWgSqAzBkTHg0FsrZS0i1T6rvsd+oKeiVHpAcuc=
            =5Nm+
            -----END PGP MESSAGE-----
          fp: 06588319109A209D639CCE51602B7725DFBDA31B
    unencrypted_regex: ^(kind)$
    version: 3.7.1
