kind: Secret
ansible_user: ENC[AES256_GCM,data:EuypMMnr,iv:jWI9+FWRfLbM7v2lSNvPdYhsGVquEmnEEeWtxaaIbxU=,tag:k+363l7t2xsfTZJD95Bfgg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:d1fJuNNvmXo=,iv:epMc7h/UfL3mEqYle3pA+N82nT3LJUMoEt6qgqYNbpw=,tag:ms5MHfOriG5KQQ06dl6eDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-10T02:44:49Z"
    mac: ENC[AES256_GCM,data:sA1dLD60zr8iVfkq3J0AAlKhkygUczF+m4OsMJPlNU68VCxb4Unh2PShiSK9F0+mXWzM26BY7TH31KJs5ROAxviu3n8wRohWaqxV2Np/i1IDJH/r2qqLmGshwMKppAMasNRmFFQ2cXLSgOzFGVhvTZN4uOKItMKlcaKd4JaLsKQ=,iv:T3Qitg8nX9oHE9fRgjaFxqXcSSGSWyEHofOOKJqYfec=,tag:xiLDtk3Ujuf4npdRB6tCcw==,type:str]
    pgp:
        - created_at: "2021-10-10T02:44:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/d+47VgAezOAQ/+LFXfh0YZ5F5noDICVAfvHYxc+Bogr+iXElSXyYtWoYNV
            1cwtPSvQ0C1Q8SGT/dEG1ltI8RNI0VC+Eg8hUFd1RTqQDtz0nUtYEs9ulkIGPbBd
            +aHr2xrvzPOKlIUdFBfexlPYF+QamW4py6FwTGppNDxMuI+YrcNQ90iuw1jP9oCW
            7LbWdj1YF6m8IXr0m3XEwrezPhrs49VbeDwO6F5sFDsac1j6YIbLYfhyRqTsPX6s
            zUi7fwBy8nXqSEK5nb3DKcnKtpd5h2R3XyQd62c2SSmt+fqhnsmDz2Wegvi7fT/T
            sD2t92wEfuipOoKHR9+e3OD9qWkTWDZF1oASgUJ9WuQdYNr/JP/17nTtRQhasFeH
            5NFvKJJ4YYJ7WhQbdzaJqJspFNcSk99TWuvuWMKoxCSh4K6BP5S26iREb2XWwo5M
            keIMD/IfsdZfOO2DEcDGbD3tJCcEhv6W4DQBZlaqA+WD+lPigK1gDxe8kRFTRGgz
            3mWusP8c85r/i5hOKnDwP6/ScIMteYbe76DmZb0bkU7ema+F8Iiblk2rQ+T+ih8M
            HI34lcW9GlUDrY4e73Fbz9B/JfMKzD6X+hkKhmXm/r5JN3AM4dsi86b/y4QaA8SA
            rZIhJNRIQBsftzkMn2MEpGrUxQkrNP04ySSu8ZdwryEp3upz65tkQO6fdLsOfybS
            XgEJTgqtRCnUa4sVJjtE+1/9MGovhQi8raz1GkPhErB1SI829CeUNXRwbGTReAVu
            KzeTrjx76dMy6/kTw8Ka+qunhoRvHuUNx8QqgPOf1rokNWhwZrygaA6pfNxn06o=
            =dtOp
            -----END PGP MESSAGE-----
          fp: 06588319109A209D639CCE51602B7725DFBDA31B
    unencrypted_regex: ^(kind)$
    version: 3.7.1
