---
# RPi uses bcmgenet as the NIC driver - alias it to net0 so bond0 can pick it up
apiVersion: v1alpha1
kind: LinkAliasConfig
name: net0
selector:
  match: link.driver == "bcmgenet"
---
# RPi leaders only have the system disk (SD card), so volumes go there
apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn
provisioning:
  diskSelector:
    match: system_disk
  minSize: 80GiB
  maxSize: 110GiB
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-hostpath
provisioning:
  diskSelector:
    match: system_disk
  minSize: 10GiB
