# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:HDkZ7AbEfuAhYSlwphJa6Q==,iv:iZ++NUKa8RxwypxOYqHWfOa0WS14z2qmfeUwmuW/6O0=,tag:7ZAYxRxJVO94fhquslk+aA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:pdmlismwIf+T7TBHEk7nAL+L,iv:ftcf7Fmw5tt2IiuKonCCUoUGxn76x5jIibGDw1j7CIg=,tag:8yDs9eHrdss7V1HMO2NEqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-12T00:18:46Z"
    mac: ENC[AES256_GCM,data:RMv3Ap0EG/Bm+Gy0mQKuaxu6/YR09O3PgKjLHoxLLGWrh7SCTISpApDDWi7v9R/2BQrBoe1dOsWTRqCMKhvlVfiElBu+Oy8Pn942as8KRdRNK8qaeSxFwnzI/1nL6wBzrbGt/V22dtA0WIhT8LixCpp10Sb1BSrypiph+8luj4E=,iv:UazNAuHI8a+03z/SKrAJTtx1gDw4KLbqdM/irQ89zms=,tag:M1YsI0QMlNN4Q7tXZaQY1Q==,type:str]
    pgp:
        - created_at: "2021-10-12T00:18:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7tAMlS9/fPMAQ//e89EUf4xMhq02pKdpnxi15nQ6mkvRO0yWPWI9DV3Dgb8
            ofbi8/MtYW9b07Ex8fTbO93cC3xNVZMSgtsXzaq9R6L9sljhRptomwJeK/d6hWOB
            9/LZ2X1F2PSdjj187SaWgVScK2RcyYbqODH20JmZ2Lln241dnZwVIdJKAgy0gCAy
            wOPhq3LgGWIyRLn1SSuV2P0rbkmMEWZvHRL/WKtLbWEQuB9PzZ5KWXs3V6E56oIi
            fUG7xoi/ngVtygryVA1j31TYARw0Bdj6Q8uoa+L63Wcy6uRl3KwheTkZtD5lDr+Z
            8WZhlThCU73xGD7oBElyum+uj7/u2LWLKwSVr4D4e4pjAzbBlxAxDY/gYGhtARtL
            H8wJfpjjYrh6nU3CdcOJ6bkcondbwJ5sDhprYttn3O8bzpAE1P/B0UKIwQQO2nQ/
            pOajyP36w8jicHwxwPCLq7VW/vXJ1Qz9+T3JBxvjR0o8Q157/MHPXx6aWfuTZJ2X
            mm9nA50esWa5s7197eQDjKbn0eNqaX77IhLed9Wyg0ZRbCgSTSGmF7y1omaq6QdZ
            Vly+uVjvUlBT8NtSjuWgV380Kg4Buet+AWkaD+4TQIZM7Ed4tqQTeA3h/NKdVR9c
            wYEAdhdbQXibMc7Q4yDsX9CpHm8GlO/wnrEAAJGq6HwSWBCnU+cugmtDbo1Q/SXS
            XgGxtXnuiYvuZ9STuxtZcyHemEiBi7eSrUgCJ+CPvuzu2vw6rMCRNK95D2+ebmrT
            XLgfzYe3iLv1WYvJprbaXDIYzKSrVgKkFEOHE7pWalBqF0TirpJ5nyr1LyNTMcg=
            =NzIZ
            -----END PGP MESSAGE-----
          fp: ED8F65FD9F30E887BE82A5A361425CB8C94EE488
        - created_at: "2021-10-12T00:18:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/d+47VgAezOAQ/9FJTZX8EnBmmdMBu2aWcBJyuaUJICg4o80598eU8lD5QG
            ngFN2BSJJJF9KvTGw9gyTbFkq7K31h2a5i6N/B+NAjQUScD/GWdT0BnOqMxAtqwA
            dewofNMRMW9zcZQfljGjDGWcrdWZaURbl3Ram7sGoTSQ+A/HrkXvN3h/c/jLdnRl
            tFc8LoBsNZgihDb3uy6Cl1Gnpcqnj918+4L1d6L5cfQadcG+vsUcRwrxFRyXuFXw
            qKO+Ybd/Nv40F9C1Qs1fFS6veXK7yVNqCEHpL5yUOSA4+H+2S3vU/KSDVGIoXISz
            h96vBp4xJOHwhCCKAHfcnc0ZxdhO/fbrkCsl3pNXA+qIhyjptFzvpwWDkG7aN3gX
            2L3mwBK3GCDrIz0fCVeknkYZXqex0cBBBqXO2ZjyHePhpOlRf4xX/U2KRLBtxzYK
            SEogRJcFwincFgaD5+1w1qtQAFR03jwYNra6EMcAjjBbgGm7PoPHBrWNYXzxICVU
            nU1zRgjbiQPkx1QN8OOKvviNHwZv1kbgBRUVNbIzHHAdFAllSWqv97KHO0drlGUi
            9h9hf66hRE0DozqUpg/d/acMz9hDXSwJKcOHmfq/Sg+oimbznULV2oWxwh5W8/on
            gfTa8I4i7DGQ3p2JkW8RMwnt7lNuENPuX3gJr43dCsLHYVtrRHzBjbElG9yr94XS
            XgFhPyRhYFP2ec53wZzYcAGpuZtCFcCBlIfcXgplCLDFGMF7VcTDBWr1jOc8SqbO
            Thg1PnS8GeAFOrOqhm1ESsNWDDTlMgrJpO0MmhIbkMJKWqd2Z78k9ZaVBqEIGIQ=
            =xiPy
            -----END PGP MESSAGE-----
          fp: 06588319109A209D639CCE51602B7725DFBDA31B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
