---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: "192.168.0.240-192.168.0.250"
  METALLB_TRAEFIK_ADDR: "192.168.0.240"
  SVC_MOSQUITTO_ADDR: "192.168.0.245"
