# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:KUeJ3lhGPK75TjAtNwINyQ==,iv:JoKx8As/cDXwzfBO3AaC+cBPLjtmN0Hbh65YRRfu6/I=,tag:J6/oty/3PRhokgkDFZgbpg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:5TMOwwVLkRF6umG1ilvuiK7q,iv:a7C1TctfIq6LLBwd7m5S4e4c2H/NNtBjgH8oi8N59L8=,tag:+slcZBsFixxP9IU8ULLnZA==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:pM4N6Q==,iv:X6bksM4MnNvykTHHQZEjBq0JQkFMR/fVBSq1J0gwcHc=,tag:5J0zg2yXNrsxmIyAsocmjg==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:JJpMLvScYn9KmEOXUTV6mV9YBZXcrPDqelVM+ZYMd3WguI5ExEubT6VLp+8rBBcQFBUFAr/irCRhiEUk4urNntx4+iJ3TRTuVPb46EFL/cKCF9hJA2czWnFgDjYKl6wsxGr0DR10+sCx9HM/5PeGxQ==,iv:mGH0kgXIVU1EjNHMo9gS0Q6w6cigyppJrrGyvEjOd40=,tag:rWS3J0AgSbC1JJCrz5w0zA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNFFkOFpaZS9ZbUVZSkRj
            SFRRay9CMjFNbEJkNjdDYWtlM0pxY0ZscDFRCnpZU3FJMWdGQ2NnS0U4cjkyYXpi
            dURJZlpZbFZmbHArRFdRNzEwbUxvMmMKLS0tIFo3VVYzaUFhYTkyMisyWWNKaUd1
            cVhkdTZlWDJVeFdDUGE2dlg2cC9vSU0K8xjsq7M+Oo+GCdGrnrPU9SUZYrZ4BI70
            eHRylHTId6nDLM9x7NQIxJgluuROG4qWkryCRcDJO83iR4zlGJZA6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-13T15:19:32Z"
    mac: ENC[AES256_GCM,data:CQmjeogGu1jE8joa8M1gmKoy+b3kbMaTcMZZpaVyh2DcltXkBCg4WxbpwMZx1LN0/BIB+8FCMo6ZhPmhkA0jUghLI9BfpYm3LE1PYYBtOaOZMYcLlOsWt3Z1Pq5x8d1vFL/5LxABAH2Ch+hn9yB/pxvYYh5yQzaI9Xe5HKcGteo=,iv:joxBGUJ5WPXwcHxYQiDWePBMQZ+Pfsu9ylJC/IZbvi0=,tag:gSHhlAb02yqWi3uW3b534Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
