apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:17vcwxSQlqbrMHdixpxP2R9dA+3pxDoYaBU3TXLNaPhsdZ9FKqtd+vBFEcW4roxv5Gs+mEAykh0geDVB+hosO1xQ4ixT9TWiY0TguVkFbW4XnyHcVHVpJV87FaNRHYyhWYtsXG1V/c2FGGPy5dup6zTi9/wfZ9vgCIe1eXeIcj4OACkISa9sJEFB13kBCwDk9r3tAQy2kjEZUmPlgmyPXqF3h/6VTX6gqwcI4o2o13M+OesR,iv:KYmeYYYpvP25mlzMtTUGMdJ3hauhgyhsIfL3306NYn0=,tag:EPCDf7qELRJWM8v7V1mpjQ==,type:str]
sops:
  age:
    - recipient: age1r0cv0zhd3uup44g0jkktl7luk0gq8dkg22d9yxtpjs380rgle3tqkj0y23
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWjEwdHV6alVac3Q5WUE0
        bGlJVXRFVTFwK2VQK285bVF5WGFzVmxZYWlnCk0zZEp6azJLMGZCcGp3SXpwS3Za
        MDNLWW9TNDBjZHNwRDFjbnh0Qy8zdUEKLS0tIDc4YldQOVVqTnREWjdEbXRDV24v
        NEdtaU05V1R3YzRkMXV4dytSNS9qT2cK62OqZ7WUvM2Ll4bJSz6Q8JoyuxloyGnV
        eCBoiLn/BDnSZCzRqfcbsjDHc/g4TMrdrT+cp3FMLtGPljVYqhpm+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-15T20:12:16Z"
  mac: ENC[AES256_GCM,data:AW+vfrZdd6Ge6kpKs0pUjSncV2MIKOuwinLeu0ZW5aur7z0S8S0o6d0ncBhSVDPHv+AWzrMmnffsmJLuZgXd3AN/rXPXDN+ECs9QRuCRtdSlacud0HH+N+jZ+elQZVyer0WE7yIfL8tLF+ArecMr+XRuVOblAf4O27/dqXCe1+c=,iv:ak8RNH3BKLyu/mr9MqPtzwGhtJZfNSguHMQ+6YLRcCw=,tag:xotEiQ453TFT12dnHogQgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
