kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mosquitto-secret
    namespace: home
stringData:
    username: ENC[AES256_GCM,data:pOUoEVCZrh+E3g==,iv:ezSc1QzuqzpXIqB/HrF9hr3aDauC69Kt0A5WeBKBveU=,tag:WTrzmB4mbKp+9FgdfyH1mQ==,type:str]
    password: ENC[AES256_GCM,data:3FO0tJH3RI0=,iv:/mYsMxPh2tk0XKJDOIxJhbZn0RbPkB54b5Eq71hjafc=,tag:/06Wqqarc/IGylIfKNSKBw==,type:str]
    mosquitto_pwd: ENC[AES256_GCM,data:JltgBXLkgKc1VRFkoj76gh633g==,iv:gWnnluKqvOLlV7VDo91JbTygsNLn1C6kHNAb9JqfHeg=,tag:DCNvJ8KVQSqIaoSUuaFGVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaVpYZjdMNlR2c0d3SVJL
            MWFob0swQmU3TXdPbGF1dXc1bGQ1WXdaUWhrCmo4dkQ5VmJSNWNQaXh0ZkZOWk1m
            Vmp2M0dRclFWVVJ4OWM2Q2NJUzAxaVEKLS0tIFJlUWxXS3V3Q1BRSXMvbEpQd2ZF
            MUJDWll5ZVp2a2tFZGhHL25SZGxRWVkKfySyVy0KoEQDdyBTFHRRJnv3qEsYraPt
            wS8KI8OYQmxtahkMH/ntXhM0tDAtnb3UFr/c9WEaQyO1bJDf2V2enw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T13:26:08Z"
    mac: ENC[AES256_GCM,data:gBHO4YFn5ETfCB6hi431b/a/ytkxSJ1KECUpm/VrPPhcDcD0cWTHwa76dWn1Uji85G0w3LQ8awjYV/UF4CpWsS6FAH27FEOl2O6zHTKJ+fAQscGlO1OIWbSWzGYCpvPCEQYopDIZaCxs/30hqTUhoe7m57KldyVVNv7T6ULfuVY=,iv:OrHUYfi+1treuFdlWpVL+paCFDGGLIg/OGa/pW1dr7Y=,tag:qwT7b57XGiFb2/y27SKYIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
