kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mosquitto-secret
    namespace: home
stringData:
    username: ENC[AES256_GCM,data:pOUoEVCZrh+E3g==,iv:ezSc1QzuqzpXIqB/HrF9hr3aDauC69Kt0A5WeBKBveU=,tag:WTrzmB4mbKp+9FgdfyH1mQ==,type:str]
    password: ENC[AES256_GCM,data:3FO0tJH3RI0=,iv:/mYsMxPh2tk0XKJDOIxJhbZn0RbPkB54b5Eq71hjafc=,tag:/06Wqqarc/IGylIfKNSKBw==,type:str]
    mosquitto_pwd: ENC[AES256_GCM,data:kXPXyG0vSCXDFS9YHDTwuFoHfm5fl8dWO9sxe9cKfs+jknGgPVZr3VlKOdr2/uDoiDiwT6ZVUjbSL+XKMKtKXdW7mM3nKkCkBGGvMG49TmnVyEnaMBQW2BxoqOxR7GXqOD4F2MGhBUvkfy28Ws93ZwvFWtepaVKEDI1d,iv:qnq0DCDL92CrbjShC0QdQGcfilGeP8G53TQFNow0d/Y=,tag:X4xOA5VBAiywRsEObkCxVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaVpYZjdMNlR2c0d3SVJL
            MWFob0swQmU3TXdPbGF1dXc1bGQ1WXdaUWhrCmo4dkQ5VmJSNWNQaXh0ZkZOWk1m
            Vmp2M0dRclFWVVJ4OWM2Q2NJUzAxaVEKLS0tIFJlUWxXS3V3Q1BRSXMvbEpQd2ZF
            MUJDWll5ZVp2a2tFZGhHL25SZGxRWVkKfySyVy0KoEQDdyBTFHRRJnv3qEsYraPt
            wS8KI8OYQmxtahkMH/ntXhM0tDAtnb3UFr/c9WEaQyO1bJDf2V2enw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T12:49:53Z"
    mac: ENC[AES256_GCM,data:oHi+L0Ti21siBLHPa0P6uh41Ye4Fb4/kE1zSkuJ6LJsCDK3UbPW8PzXuR4o0wLFbHlXyFoFXV0TZ7/5uB+6VagvVlnvHdzXf+rbpDHZwr1MMkErUpWPEfJ64sq8h7TRab/VmAimRPy3gwQ/le+KrhzgCi/2jqaUhKuSb8KpTW+Q=,iv:D9w8K3zCtBr93XiZBW/W1CEIDjCI1nYdqfEcFmfQ7cM=,tag:GlMwcOSDuee9/+NvzSa8sw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
