---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-red
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      node-red:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: docker.io/nodered/node-red
              tag: 4.0.8
            envFrom:
              TZ: ${TIMEZONE}
              NODE_RED_ENABLE_SAFE_MODE: "false"
              NODE_RED_ENABLE_PROJECTS: "true"
            resources:
              requests:
                cpu: 22m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: node-red
        ports:
          http:
            port: 1880
    ingress:
      app:
        className: "nginx"
        annotations:
          hajimari.io/icon: mdi:sitemap
        hosts:
          - host: &host "node-red.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        existingClaim: config-node-red-0
        advancedMounts:
          node-red:
            app:
              - path: /data
