# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-red
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          node-red:
            image:
              repository: docker.io/nodered/node-red
              tag: 4.0.8
              pullPolicy: IfNotPresent
            env:
              TZ: "${TIMEZONE}"
              FLOWS: flows.json
              NODE_RED_ENABLE_PROJECTS: "true"
              NODE_RED_ENABLE_SAFE_MODE: "false"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 22m
                memory: 164M
              limits:
                cpu: 300m
                memory: 262M
            podSecurityContext:
              privileged: true
    service:
      node-red:
        controller: main
        ports:
          http:
            port: 1880
    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          hajimari.io/icon: mdi:sitemap
        hosts:
          - host: &host "node-red.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: config-node-red-0
        globalMounts:
          - path: /data
