apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:0PJQzMOEiZi0oAKbbsLJhR5tONu5CcSBZYQWTv2YINZ13kI0QEB7lw==,iv:hmCQxx393n/uwXhHS8AkQU/1GImdzxgWzD8H8dRP+wU=,tag:CuWi03KamLpLroZyUECkcw==,type:str]
sops:
  age:
    - recipient: age1r0cv0zhd3uup44g0jkktl7luk0gq8dkg22d9yxtpjs380rgle3tqkj0y23
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOWlPTlNwYWlycVpyZ1du
        dm9vekdER0tGOHZhZXVadkxFSDVZSTVod2xZCjcyVklKTFgxVllBam1UT2NrTVZs
        VTdGNmx4OFJmYjN4b29ranQ1REFLTVkKLS0tIFFZOWRLamcyL2NVOTBqQmpDZUxw
        eXEyaVlTc1ZnczhhWW5INTVjaHA3b2MK1yQkBp4CgUzPjjvzinSS8JSD4tpo2qGv
        CUAA2zxL60CInU1DhBi09A/PquKB2D0lN2NkQi3pljSvFB56BSq4Pw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-15T20:12:16Z"
  mac: ENC[AES256_GCM,data:1OIwApiVTF530rqZ0W/1008njnr01fPVjnPlE/YUyP8K+2aNVxNa+G+hgYN/EXirHtS9CBsquz/rSdVt3lfXS9b4qbjAE0LQTRfGD/6/a30FzUGUcJQKNJs1ZzqVSrAVUtZC4W6SPWIzaYEl5VsJaap8mBCly7INnhoQkI5ao60=,iv:RJ3QugeUUm+GjYUw0fldzRsr9vVZxbw3vJYE5vKNzOU=,tag:0PjvzIuAKgjYRNf2UZnVgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
