---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zwave
spec:
  chartRef:
    kind: OCIRepository
    name: zwave
  interval: 1h
  values:
    controllers:
      zwave:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/zwave-js/zwave-js-ui
              tag: 11.22.0@sha256:f24115c115f98a1cd69fea620bf20180be17889e9ae3c58ceabf5df1bc56c2a8
            env:
              TZ: America/New_York
              PORT: &port 80
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
        pod:
          nodeSelector:
            aeotec.feature.node.kubernetes.io/zwave: "true"
    service:
      app:
        ports:
          http:
            port: *port
          websocket:
            port: 3000
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: zwavejs2mqtt.png
          gethomepage.dev/name: Zwave
          gethomepage.dev/group: Home
          gethomepage.dev/pod-selector: app.kubernetes.io/name=zwave
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /usr/src/app/store
      usb:
        type: hostPath
        hostPath: /dev/ttyACM0
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/ttyACM0
      tmp:
        type: emptyDir
