apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:qrP4rcJuA3k4a2ZgpgxMZw==,iv:ryvJfWSFFxUeITA1A9/MjLkv8KyqEd2ZycKM/q1qCYI=,tag:/uHktSi/TUeEY63zIBNA/A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:+XcqQCXCo3CHMhx3LwjHTX2e,iv:IyvAF5INbX/IQm+sElkuBrSYvyEj1UlZCHm87fpb7/c=,tag:jykLqXqTgrL4ua4KEQ9qsA==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:JcMvWaMZCRMHgA==,iv:S7/HGCLI0yfk/owFUdNn9874KDPgEWi/T9wXTtPAAoE=,tag:ui+bWIsjvLJm0gXwg/nUUA==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:VfIFuF02PyQ=,iv:5Sk5rmSom9F3bwSa0ZDbYJZdSGaJY8ZBdqIv/hmSzdo=,tag:c+BljptxGiQD+1FY2HHn1w==,type:str]
    SECRET_PUSHOVER_USERKEY: ENC[AES256_GCM,data:iF6TCSS7zKmukdepbyzVwppq1JncCuBu53g1D4KY,iv:TKG7BGDqRqZvSibCBCmcjuuV5KI15sfcMpjtCkYhBhk=,tag:GbhYUvN8eTlGerSXxwcuXQ==,type:str]
    SECRET_PUSHOVER_ALERT_MANAGER_APIKEY: ENC[AES256_GCM,data:rbWrPnDVeeYG4J6Ewg+eQnIwbqYeHq4hIrfGlI11,iv:5DBnwa54Kskxk75riAQkmJhGm2n3apLcd+8u2qNoq4c=,tag:/wM4liJUlHrgS5PywsBdgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSekl0ekNHYUZiWlNNWlVQ
            bzdUYzNUeVV0cUFTUFZEb3h3b054L1d5eVd3CnF4TTRyZFd1QlpkN2Q2eFkwUXl4
            ME40YzMzSEEwbzhpOElOSDBBM0p3bVkKLS0tIGpoV0l1cG0yZUZmSzd2L0lyamgz
            WEEvZ3hUcXNVZXdhNWZGYzI1MEs5SXcKNjAsz+D4I38f+LtY+BQy6Obt+qf+q9Ih
            ZxE7eOWexLaNSv2V5G/6VxP871a5WHAYuMPdJsJ4i3C6VqVe8vLymQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-23T19:18:14Z"
    mac: ENC[AES256_GCM,data:2nVPM+4NGp8CADuSs23DiJI4eXbee1E64mlgb589d1vhztwou5Iy58CWtmFnD5qoaw5T3EEuQvcZsCJwmJAZIsW7WvK/N7pzp92QP+PxHAY1KPpzvZrh8pWhvu2RP6SUAtEyjlO2QOuOzwvCIueR++YcDtZvGM0QjO4os32jgJk=,iv:UxWVPaeSdALKrrT9PQvk8hKlwqAYA4bsGoxBhZ6DsM0=,tag:/Og9tr+i4dVhIn924FM2iQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
