apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:qrP4rcJuA3k4a2ZgpgxMZw==,iv:ryvJfWSFFxUeITA1A9/MjLkv8KyqEd2ZycKM/q1qCYI=,tag:/uHktSi/TUeEY63zIBNA/A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:+XcqQCXCo3CHMhx3LwjHTX2e,iv:IyvAF5INbX/IQm+sElkuBrSYvyEj1UlZCHm87fpb7/c=,tag:jykLqXqTgrL4ua4KEQ9qsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSekl0ekNHYUZiWlNNWlVQ
            bzdUYzNUeVV0cUFTUFZEb3h3b054L1d5eVd3CnF4TTRyZFd1QlpkN2Q2eFkwUXl4
            ME40YzMzSEEwbzhpOElOSDBBM0p3bVkKLS0tIGpoV0l1cG0yZUZmSzd2L0lyamgz
            WEEvZ3hUcXNVZXdhNWZGYzI1MEs5SXcKNjAsz+D4I38f+LtY+BQy6Obt+qf+q9Ih
            ZxE7eOWexLaNSv2V5G/6VxP871a5WHAYuMPdJsJ4i3C6VqVe8vLymQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-23T01:55:45Z"
    mac: ENC[AES256_GCM,data:fFF/q3Jv9se7yFggm+4pwoIRudH4lkngS0+OAII6ESweaM3gqjpzDXZGpr27HZHVD1x7/ph4l15XyMGR3nwWy+OMEthS0jy9nQdpzCBVyy8aAWJIfSRVDpc2sxANpeacZ4fyHKE/Ttlbtzu85RcrMvDqFMC9Au+dJqdey19P6GE=,iv:fR9I9XvDLwT3VGTX5OQ2OfJJ3D8bWPV4gPUeViaa7Y4=,tag:I7b0vSibjpQIhJeOcEo9cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
