---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: system_disk  # Keep it on the system disk
  minSize: 2GB
  maxSize: 80GB
  grow: false
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn
provisioning:
  diskSelector:
    match: system_disk  # Use the same system disk
  minSize: 80GiB
  maxSize: 100GiB
