---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: esphome-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secrets.yaml: |
          api_encryption_key: "{{ .ESPHOME_API_ENCRYPTION_KEY }}"
          ota_password: "{{ .ESPHOME_OTA_PASSWORD }}"
  data:
    - secretKey: ESPHOME_API_ENCRYPTION_KEY
      remoteRef:
        key: esphome
        property: ESPHOME_API_ENCRYPTION_KEY
    - secretKey: ESPHOME_OTA_PASSWORD
      remoteRef:
        key: esphome
        property: ESPHOME_OTA_PASSWORD
