---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-config-v1
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
