# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant
    namespace: home
stringData:
    HASS_LATITUDE: ENC[AES256_GCM,data:GdRyLBYj/qTn,iv:QkJDG9gzxNccFuBoFlmdkEgRAHLb6fsRguADs8izdE8=,tag:rhZr0KIwCoUSDoAhsvRFLQ==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:RJFyinDLTVZvHw==,iv:bga6e7+3+hJ4BQcWEMMM3OKDBSH9POptpRT7CujFGEY=,tag:zrW7tTgfz/3SMO/MsKyJCg==,type:str]
    HASS_PIRATE_WEATHER_API_KEY: ENC[AES256_GCM,data:KPGRR5LY+Y3wG/tbZ1OXoS8pGHn1JzW8jkdVrrLaF8KwARFQgJ4YWg==,iv:GtONFnaWi1aMFTbnS+qFKAh6+jeTNgW872KqpZKtEVs=,tag:X2b0xbOPHHbUgNcMuWm6XA==,type:str]
    HASS_CLOUD_EMAIL: ENC[AES256_GCM,data:PCzjr6J3LaLuMvuJXF48QdV2eg==,iv:FdWvheSc7GTDvglHwOsyFgbJQvU8b/80Fl1RZF9DP1g=,tag:iYgbdKgmjlaEu866vHE67w==,type:str]
    HASS_CLOUD_PASSWORD: ENC[AES256_GCM,data:rzINq41fOf4=,iv:LpB0WLdOiCZieKVRMNn2T20Uu/7fXJwsMS8PZL+6iJs=,tag:DfvrZCAQ5/7Ri8GX1vCigA==,type:str]
    HASS_EMAIL: ENC[AES256_GCM,data:Jw/5BGqL9lZVfQktjaSaMQuP,iv:qL7HTo5P/FMZ4grsJtTYZdmEXDeHNM+t96QgWN2AIU0=,tag:K7Hnh4xAfGJmyGLxqIqLoQ==,type:str]
    HASS_DAIKIN: ENC[AES256_GCM,data:SWy9avY737/h/+dfnQ==,iv:YQ9KZw9T8HAAmbYbFvDVjb4m7y9Wtv/5msE+ipStQpI=,tag:9chmnaH3xy6lddPkiKKlKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZTRsNU5jd3dEY3BzZ3ZE
            aEQ1aVJqS2ZMNUw5K3BMZTlHc0psMDNoeEJjCm8wMElPQ0dXcUpGTXZDWDNQOXJn
            YWQzQ2dtQnl6MXF4bS9xNUwwRHFKYWsKLS0tIFNBOHZrRWpXM1ROYmZ2aXhGdldN
            VTNPSW5MV0xpbmtTVGNzb0kxc25xNHcK/gCTMxZBaEGERoq7Xc8upsf7OYe/MFk0
            TYU38MinytF8dKP+G2yqL/caBcTGXv4ynWLxuua/afvBhLMnyuXHLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T00:40:55Z"
    mac: ENC[AES256_GCM,data:QVQ/TYVm9mHAP+wmK+Ra7xzkbniH+v4D9vOaji/udKJJNiXIp/KtiwGvEmsYJC0B38P07HzEI5H0BQRmrR6zHDHtsoNIIjRVTWBUAmnjAmVpogZ7RvuRNhBZVZyKttffNkgtdOudn9UOCzYh/4O4e4GMAMADjQ54QxhYxP5RtUY=,iv:dYy0L77/oAHuXheYUm11+0Yqm4l9w+BDgx6IHy8DCzs=,tag:kQISBjXutUzP8CVWd78pFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
