# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:aytpHBzUv9uo83aWI4lk1RxQuSzKYFOahWBV+d0QdJqq5vE7BA==,iv:ifmo90CegsfFleL4hGIqxb8qFv/1LjpKJ6cePCByqwY=,tag:Tf9Un1PSLp+EhvlPJVKmDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OC9TNGIwT3BoV2NtenUr
            b0JVU2ltdGo2QUx5QjJEZmZaN2dNZlFEbEI0CnNTYWp0aE9zVm1CdkxoaWZsUUVE
            RVE4YndnT1dGS1Q5VmViMFFocWpQK3cKLS0tIEJXYjZrKzMvQ3pIRHZhbE1CRGNE
            R2NSNTZscjRCRVFHTWJYam9pVVBqbncKqVAMIeVyl/iMpXkw3gw+nugwFIZXvalf
            IR8Tczt6WDXOlJocWKi/SDW6soFgSVPdbIn5yq4xDPtdkGmPazbq/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-09T23:08:44Z"
    mac: ENC[AES256_GCM,data:W1R/xUSaqNEqpj8TVEAXUEX8F2pSY8ryIaIQctjVjG/2TXz8Qj8fA9hjhXNstoYdghj+rfSBPu8dbDDwdc22H5Xhn37SAleWSZfiICgBBhXgmcKS6aJl4Cv1MJpQNUr2OF7EMdhoQLEquR7S4mtohhMcO21pgkpuHZkyceBGApE=,iv:4uCMVZHIWSjwzFSTBouOG3sF4Tc4AQ8zmdPeoe1ybVc=,tag:3HG5iTjeWofxpaZNNbMLiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
