---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 10.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: home-assistant
      namespace: home
  values:
    initContainers:
      npm-update-modules:
        image: node:18-buster-slim@sha256:a267345a91466fcd852094da0f297f299f95ca78d97de0d0e0bece0d3f2079e6
        command: ["npm", "update", "--verbose"]
        workingDir: /data
        volumeMounts:
          - name: config
            mountPath: /data
    image:
      repository: ghcr.io/k8s-at-home/node-red
      tag: v2.2.2
    env:
      TZ: "America/New_York"
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_ENABLE_SAFE_MODE: "false"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "resistor-nodes"
        hosts:
          - host: "node-red.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "node-red.${SECRET_DOMAIN}"
            secretName: "node-red-tls"
    persistence:
      config:
        enabled: true
        existingClaim: node-red-config-v1
        mountPath: "/data"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
