# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:V4w5uT7kmEmdDtqj0k9kdf5j1h5+ig6VevnhkEyxwB0lTVQ1LA==,iv:KqUMn9PLzJrufqoebuPB440WbO3M30lXWpZBZKovhS4=,tag:suGGpY2/feLiTxuMyDWQ3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snuf5u3a0knusa8qfqpqm52k0lae2ma5mm86pvng4wcgr5cu8uasww94ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoU3FLN1ZISVA2R3BWZlcz
            VUJQbWZINUlLR3BoSHpaZlRnSGlLQkljYUVrCjZ6cDlxZWkyZXJVcE1qSXprOHgr
            ZmVPWnV2WFg2QkJ5K2sxZVlYVzRsNUUKLS0tIDBHNCtPN1AxS3dVbHdlYVV6MGJD
            QzA3MGs3TUgzNC91VkRhaDJJVForVGsKb4FpzLlE5Er2aoP3aa1IAWFUnyH1zKIE
            5kvMD8vXbjJzwznmlE9grPm6CcIyHB8kdK09QO/WMYcr6ZkBUcgliQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-25T16:48:25Z"
    mac: ENC[AES256_GCM,data:FQsfGSH5CqIFgVszj3/xrHWFwXTFFRDcBV3QOlWk/m8hgclH5IyREi1YrKEDJxzV/cYfCStcWX7ejgpET1JoFzJP8u+OSvOAQgz4MHyA2xLmDGeG9loVtPXMpJtMuFryF+RDkGh3ll58J1efWIwYhZpLa7RKwy0Dyg3CNPD3fI0=,iv:cuplCoF7X4ejou1OeEwcPoeyvpdlf+1rxssC9agE+cM=,tag:MrXwWZSdMHywuuAvnKIlZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
