---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: decluttarr
spec:
  chartRef:
    kind: OCIRepository
    name: decluttarr
  interval: 1h
  values:
    controllers:
      decluttarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/manimatter/decluttarr
              tag: v2.2.0@sha256:fd3dc206c17df32190cda1bed2ef3ee1cb9726bd108aa7e97e83e47cb3e72d78
            env:
              TZ: America/New_York
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/logs
      secret-file:
        type: secret
        name: "{{ .Release.Name }}-secret"
        globalMounts:
          - path: /app/config/config.yaml
            subPath: config.yaml
